# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
# en:
#   languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en
en:
  languageCode: en-us
  weight: 2
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh-Hant:
 languageCode: zh-Hant
 weight: 1
 contentDir: content/zh-Hant
 params:
   description: Site description in Chinese...

